- Media:
    - Jellyfin:
        href: http://jellyfin.${DOMAIN}
        description: Player
    - Jellyseerr:
        href: http://jellyseer.${DOMAIN}
        description: Requests
    - Qbittorrent:
        href: http://qbittorrent.${DOMAIN}
        description: Torrents
    - Prowlarr:
        href: http://prowlarr.${DOMAIN}
        description: Indexer Manager
    - Sonarr:
        href: http://sonarr.${DOMAIN}
        description: TV Shows
    - Radarr:
        href: http://radarr.${DOMAIN}
        description: Movies
