- Media:
    - Jellyfin:
        href: http://jellyfin.${DOMAIN}
        description: Player
    - Jellyseerr:
        href: http://jellyseer.${DOMAIN}
        description: Requests
    - Qbittorrent:
        href: http://qbittorrent.${DOMAIN}
        description: Torrents
